### PR TITLE
Raspberry Pi RP2040

### PR DESCRIPTION
**Pull request by JeremyGrosser**
The "size" is set at the peripheral level and inherited by the registers within that peripheral. I couldn't find a good way to make svd2ada copy the size from the peripheral if it's not set on the register, so I modified the SVD file instead. I've kept the modifications as a separate diff here so that it can be reverted if svd2ada gains support for this type of inheritance.

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
Thanks @JeremyGrosser, it would be nice to fix `svd2ada` on this inheritance issue.

@pat-rogers do you think it is doable?

**Comment by Fabien-Chouteau** [comment]
BTW @JeremyGrosser , if you are working on a BSP for the Pico/RP2050 we should share our efforts.
I have one shipping to me at this time and I plan to make a full driver and BSP crate for Alire.

**Comment by JeremyGrosser** [comment]
I've got zfp-cortex-m0p running and toggling a GPIO pin here: https://github.com/JeremyGrosser/rp. That repo is just me playing with the new chip right now, it's not meant to be compatible with ADL HAL yet.

I started on bb-runtimes, but the linker isn't copying the .boot2 section to the program binary (it does get included in libgnat.a) https://github.com/AdaCore/bb-runtimes/compare/master...JeremyGrosser:rp2040

The datasheet suggests that future versions of this chip will be named RPxxxx, so we should keep that in mind when naming/organizing the BSP.

**Comment by pat-rogers** [comment]
On 28-Jan-21 3:26 AM, Fabien Chouteau wrote:
> Thanks @JeremyGrosser <https://github.com/JeremyGrosser>, it would be 
> nice to fix |svd2ada| on this inheritance issue.
> 
> @pat-rogers <https://github.com/pat-rogers> do you think it is doable?

I don't know just yet, need to take a look. If we can programmatically 
avoid having to change the SVD files that would definitely be desirable!


Best regards,

Pat

--
Patrick Rogers, PhD
rogers@adacore.com
+1 646 375 0739

**Comment by Fabien-Chouteau** [comment]
> I've got zfp-cortex-m0p running and toggling a GPIO pin here: https://github.com/JeremyGrosser/rp. That repo is just me playing with the new chip right now, it's not meant to be compatible with ADL HAL yet.

That's great! So you have the first Ada code running on the PICO!
Do you have a twitter account to share this with the world? ^^

**Comment by JeremyGrosser** [comment]
Unsurprisingly, I am @JeremyGrosser on twitter. https://twitter.com/JeremyGrosser/status/1354848621024305157

**Review by Fabien-Chouteau — APPROVED** [review]
@pat-rogers I think we are good to go on this PR.

**Pull request merged**
